### PR TITLE
Update readme for m2x V2.0 and add new example.

### PR DESCRIPTION
**Pull request by edgarsilva**

### CODE REVIEW

**Comment by stewart** [comment]
The example should be nested in a folder so `import-examples` can grab it for the site - it also shouldn't need a JSHint comment - the `.jshintrc` should take care of it.

**Comment by edgarsilva** [comment]
Will move and update, yeah the jshint stuff got carried over on copy pastes... I will remove.

**Comment by edgarsilva** [comment]
wait a sec with this, making some more changes

**Comment by stewart** [comment]
:telephone_receiver:

**Pull request merged**
